#!/usr/bin/env bash
set -euo pipefail

# LoJix FM installer for Ubuntu (aaPanel host)
# Usage: sudo ./install_lojix.sh

GIT_REPO="https://github.com/triel-technologies/lojix-fm.git"
DOMAIN="lojix.my.id"
SITE_ROOT="/www/wwwroot/${DOMAIN}"
PROJECT_DIR="${SITE_ROOT}/lojix-fm"

# DB credentials for the site (from your aaPanel settings)
SITE_DB_NAME="sql_lojix_my_id"
SITE_DB_USER="${SITE_DB_NAME}"
SITE_DB_PASSWORD="511cee1f4f2f78"

echo "== LoJix FM installer =="

if [ "$EUID" -ne 0 ]; then
  echo "Please run as root: sudo $0" >&2
  exit 1
fi

which docker >/dev/null 2>&1 || {
  echo "Installing Docker..."
  apt update
  apt install -y ca-certificates curl gnupg lsb-release git
  mkdir -p /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" |
    tee /etc/apt/sources.list.d/docker.list > /dev/null
  apt update
  apt install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
  systemctl enable --now docker
}

echo "Creating site folder ${SITE_ROOT}"
mkdir -p "${SITE_ROOT}"
chown root:www-data "${SITE_ROOT}" || true
chmod 755 "${SITE_ROOT}"

if [ -d "${PROJECT_DIR}" ]; then
  echo "Project directory already exists at ${PROJECT_DIR}, pulling latest..."
  cd "${PROJECT_DIR}"
  git pull || true
else
  echo "Cloning repository into ${PROJECT_DIR}..."
  git clone "${GIT_REPO}" "${PROJECT_DIR}"
fi

cd "${PROJECT_DIR}"

if [ ! -f ".env" ]; then
  echo "Generating .env from .env.template (secrets kept locally)"
  ROOT_MYSQL_PASS=$(tr -dc 'A-Za-z0-9!@#$%_-^' </dev/urandom | head -c 24 || echo 'rootchangeme')
  cp .env.template .env
  sed -i "s|DB_USER=.*|DB_USER=${SITE_DB_USER}|" .env || true
  sed -i "s|DB_PASSWORD=.*|DB_PASSWORD=${SITE_DB_PASSWORD}|" .env || true
  sed -i "s|MYSQL_ROOT_PASSWORD=.*|MYSQL_ROOT_PASSWORD=${ROOT_MYSQL_PASS}|" .env || true
  sed -i "s|DB_NAME=.*|DB_NAME=lojixfm|" .env || true
  sed -i "s|DOMAIN=.*|DOMAIN=${DOMAIN}|" .env || true
  echo "# Generated by install_lojix.sh on $(date)" >> .env
  echo "MYSQL_ROOT_PASSWORD=${ROOT_MYSQL_PASS}" >> .env
  echo "Created .env (secrets only on server)."
else
  echo ".env already exists, leaving it untouched."
  ROOT_MYSQL_PASS=$(grep -E '^MYSQL_ROOT_PASSWORD=' .env | cut -d'=' -f2- || true)
fi

echo "Starting Docker Compose stack (may take a while)..."
docker compose pull || true
docker compose up -d

echo "Waiting for MySQL container to be ready..."
set +e
for i in {1..60}; do
  if docker exec lojix-mysql mysqladmin ping -uroot -p"${ROOT_MYSQL_PASS}" --silent &>/dev/null; then
    echo "MySQL is up"
    break
  fi
  sleep 2
done
set -e

echo "Creating site database and user '${SITE_DB_USER}'"
docker exec -i lojix-mysql mysql -uroot -p"${ROOT_MYSQL_PASS}" <<SQL
CREATE DATABASE IF NOT EXISTS \\`${SITE_DB_NAME}\\`;
CREATE USER IF NOT EXISTS '${SITE_DB_USER}'@'%' IDENTIFIED BY '${SITE_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON \\`${SITE_DB_NAME}\\`.* TO '${SITE_DB_USER}'@'%';
FLUSH PRIVILEGES;
SQL

if [ -f "./mysql/init/init.sql" ]; then
  echo "Importing initial schema into ${SITE_DB_NAME}"
  docker exec -i lojix-mysql mysql -uroot -p"${ROOT_MYSQL_PASS}" ${SITE_DB_NAME} < ./mysql/init/init.sql
fi

echo "Installer finished. Next steps:"
echo "- In aaPanel, create site: Domain ${DOMAIN}, Path ${SITE_ROOT}, PHP version PHP-83 (as you requested)."
echo "- If desired, add the Apache reverse proxy config from 'apache/lojix.my.id.conf' into aaPanel's vhost for ${DOMAIN} or use it to verify settings." 
echo "- The application's .env was created at ${PROJECT_DIR}/.env (contains generated secrets)."
echo "- phpMyAdmin is available on the host at 127.0.0.1:13002 (only locally). To access, use ssh -L 13002:127.0.0.1:13002 root@${DOMAIN}" 
echo "- To view logs: cd ${PROJECT_DIR} && docker compose logs -f"

exit 0
